---
# apt-repo-sury-org/tasks/main.yml

- name: install required packages
  package:
    name:  '{{ item }}'
    state: present
  with_items: '{{ apt_repo_sury_org__requires }}'
  tags:
    - packages
    - apt_repo_sury_org

- name: add ppa:ondrej/php (Ubuntu case)
  apt_repository:
    repo: 'ppa:ondrej/php'
  when: ansible_distribution == 'Ubuntu'
  tags:
    - repos
    - packages
    - apt_repo_sury_org

- name: add packages.sury.org (Debian case)
  block:
    - name: add gpg repo key
      apt_key:
        url:  'https://packages.sury.org/php/apt.gpg'
        state: present

    - name: add apt repo
      apt_repository:
        repo:  'deb https://packages.sury.org/php/ {{ ansible_distribution_release|lower }} main'
        state: present
        filename: php
  when: ansible_distribution == 'Debian'
  tags:
    - repos
    - packages
    - apt_repo_sury_org
